name: Build and Deploy Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX (for PDF generation)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra texlive-plain-generic

      - name: Convert Markdown to HTML Website
        run: |
          pandoc resume.md --template=template.html -o index.html

      - name: Convert Markdown to PDF Document
        run: |
          pandoc resume.md -o resume.pdf

      - name: Upload production assets to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
