name: Build and Deploy RenderCV Resume

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install RenderCV and Dependencies
        run: |
          pip install "rendercv[full]"
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra


      - name: Run RenderCV Compiler
        run: |
          rendercv render resume.yaml

      - name: Prepare Assets for Static Web Hosting
        run: |
          # RenderCV builds files inside a directory named "rendercv_output"
          # Move the compiled assets into the root folder for deployment
          cp rendercv_output/Will_Vestergaard_CV.pdf ./resume.pdf
          cp rendercv_output/Will_Vestergaard_CV.html ./index.html

      - name: Upload production assets to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
